import { Download, FileText, User, BarChart3, AlertCircle } from "lucide-react";
import { toast } from "sonner";
import { periodData, pastReports } from "./mockData";

const dancers = periodData.today.dancers!;

export function ReportsTab() {
  const handleExport = (label: string) => {
    toast.success(`Downloading ${label}…`, { duration: 2000 });
  };

  const todayStr = new Date().toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" });

  return (
    <div>
      <h2 className="font-heading text-3xl tracking-wide mb-6">Reports & Exports</h2>

      {/* Section 1 — Quick Export Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
        {[
          { Icon: FileText, title: "Tonight's Shift Report", desc: "All door + room entries, totals", format: "Export CSV", label: "Tonight's Report — CSV" },
          { Icon: User, title: "Dancer Payroll Sheet", desc: "Net payout owed per performer", format: "Export PDF", label: "Dancer Payroll — PDF" },
          { Icon: BarChart3, title: "Full Period Revenue Report", desc: "Aggregated data for selected range", format: "Export CSV", label: "Full Period — CSV" },
        ].map((card, i) => (
          <div key={i} className="glass-card p-6 flex flex-col justify-between">
            <div>
              <card.Icon className="w-6 h-6 text-primary mb-2" />
              <h3 className="font-heading text-xl tracking-wide mb-1">{card.title}</h3>
              <p className="text-muted-foreground text-sm mb-4">{card.desc}</p>
            </div>
            <button
              onClick={() => handleExport(card.label)}
              className="flex items-center justify-center gap-2 w-full px-4 py-2.5 rounded-lg border border-border text-sm text-muted-foreground hover:text-foreground hover:border-primary/40 transition-all"
            >
              <Download className="w-4 h-4" /> {card.format}
            </button>
          </div>
        ))}
      </div>

      {/* Section 2 — Report Preview */}
      <div className="glass-card p-6 mb-8">
        <h3 className="font-heading text-2xl tracking-wide mb-4">Report Preview — Tonight</h3>
        <div className="bg-background border border-border rounded-xl p-6 font-mono text-sm leading-relaxed overflow-x-auto">
          <pre className="text-foreground whitespace-pre-wrap">
{`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
         2NYT SHIFT REPORT
         ${todayStr}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DOOR SUMMARY
  Total Guests:          94
  Door Revenue:       $1,880
  New Guests:            62
  Returning Guests:      32  (34%)

ROOM SUMMARY
  Total Sessions:        18
  Room Revenue:       $2,250
  Avg Session Time:   12 min
  Peak Hour:          11PM

FINANCIAL SUMMARY
  Gross Revenue:      $4,130
  House Net:          $3,478
  Dancer Payouts:       $652

DANCER BREAKDOWN
${dancers.map(d => `  ${d.name.padEnd(16)}${d.sessions} session${d.sessions > 1 ? 's' : ' '}    ${d.netPayout < 0 ? `Owes:   -$${Math.abs(d.netPayout)} [!]` : `Payout: $${d.netPayout}`}`).join('\n')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`}
          </pre>
        </div>
      </div>

      {/* Section 3 — Past Reports Log */}
      <div className="glass-card p-6 mb-8">
        <h3 className="font-heading text-2xl tracking-wide mb-4">Past Reports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border text-muted-foreground">
                <th className="py-3 px-2 text-left font-medium">Date</th>
                <th className="py-3 px-2 text-left font-medium">Type</th>
                <th className="py-3 px-2 text-left font-medium">Period</th>
                <th className="py-3 px-2 text-left font-medium">Generated By</th>
                <th className="py-3 px-2 text-center font-medium">Action</th>
              </tr>
            </thead>
            <tbody>
              {pastReports.map((r, i) => (
                <tr key={i} className="border-b border-border/30 hover:bg-primary/5 transition-colors">
                  <td className="py-3 px-2 text-foreground">{r.date}</td>
                  <td className="py-3 px-2 text-foreground">{r.type}</td>
                  <td className="py-3 px-2 text-muted-foreground">{r.period}</td>
                  <td className="py-3 px-2 text-muted-foreground">{r.by}</td>
                  <td className="py-3 px-2 text-center">
                    <button
                      onClick={() => handleExport(`${r.type} — ${r.date}`)}
                      className="px-3 py-1 rounded-lg text-xs border border-border text-muted-foreground hover:text-foreground hover:border-primary/40 transition-all"
                    >
                      <Download className="w-3 h-3 inline mr-1" /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
